### PR TITLE
More options

### PR DESCRIPTION
**Pull request by cosmo0**
- Latest RA versions already have ffmpeg support.
- More options for launching a command line, recording gameplay, saving to USB.

### CODE REVIEW

**Comment by andybalaam** [comment]
Thank you!

Your change reverts some of the edits I made this morning - please could you fix that?

**Comment by andybalaam** [comment]
Also, I'd be happy (maybe as a separate change) to remove the patching and recompiling step completely, and just say "make sure you use X version of RetroArch (and here's how to check)" or similar.

**Comment by cosmo0** [comment]
Done!

Removing the RA recompiling would require to specify which version started integrating ffmpeg, and I couldn't find it ^^'

**Comment by andybalaam** [comment]
Awesome, thank you - merged!

**Comment by andybalaam** [comment]
> Removing the RA recompiling would require to specify which version started integrating ffmpeg, and I couldn't find it

Naming a version that definitely doesn't need it, even if it's higher than strictly necessary, would be fine.

**Comment by cosmo0** [comment]
Mine is RA 1.8.8.

**Pull request merged**
